### ISSUE TITLE
Plugin crash when aborting cluster creation

### ISSUE THREAD

**Issue by uhinze** [syseleven/terraform-provider-metakube#24]
Cluster was stuck in creation because of invalid service CIDR. When I Ctrl+C the Terraform process, I get:

```
panic: close of nil channel
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: 
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: goroutine 189 [running]:
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).stop(0xc0003575e0)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:201 +0x71
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).Stop(0xc0003575e0, 0x22b1680, 0xc0009a69f0, 0xc0009a6a80, 0xc0003575e0, 0xc0009a69f0, 0xc000530ba0)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:215 +0xa5
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_Stop_Handler(0x2059180, 0xc0003575e0, 0x22b1680, 0xc0009a69f0, 0xc000300960, 0x0, 0x22b1680, 0xc0009a69f0, 0x0, 0x0)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:434 +0x214
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000cf6c0, 0x22bf260, 0xc000503500, 0xc0003f2700, 0xc000907500, 0x2ae4508, 0x0, 0x0, 0x0)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: google.golang.org/grpc.(*Server).handleStream(0xc0000cf6c0, 0x22bf260, 0xc000503500, 0xc0003f2700, 0x0)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000700320, 0xc0000cf6c0, 0x22bf260, 0xc000503500, 0xc0003f2700)
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-02T09:35:47.651+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.1:         google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021/02/02 09:35:47 [TRACE] GRPCProvider: Stop
2021-02-02T09:35:47.654+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/02/02 09:35:47 [DEBUG] metakube_cluster.default: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/02/02 09:35:47 [TRACE] EvalMaybeTainted: metakube_cluster.default encountered an error during creation, so it is now marked as tainted
2021/02/02 09:35:47 [TRACE] EvalWriteState: removing state object for metakube_cluster.default
2021/02/02 09:35:47 [TRACE] EvalApplyProvisioners: metakube_cluster.default has no state, so skipping provisioners
2021/02/02 09:35:47 [TRACE] EvalMaybeTainted: metakube_cluster.default encountered an error during creation, so it is now marked as tainted
2021/02/02 09:35:47 [TRACE] EvalWriteState: removing state object for metakube_cluster.default
2021/02/02 09:35:47 [WARN] Early exit triggered by hook: *terraform.stopHook
2021/02/02 09:35:47 [TRACE] vertex "metakube_cluster.default": visit complete
2021/02/02 09:35:47 [TRACE] dag/walk: visiting "metakube_node_deployment.default"
2021/02/02 09:35:47 [TRACE] vertex "metakube_node_deployment.default": starting visit (*terraform.NodeApplyableResourceInstance)
2021/02/02 09:35:47 [TRACE] dag/walk: visiting "local_file.kubeconfig"
2021/02/02 09:35:47 [TRACE] vertex "local_file.kubeconfig": starting visit (*terraform.NodeApplyableResourceInstance)
2021/02/02 09:35:47 [TRACE] GRPCProvider: Stop
2021-02-02T09:35:47.654+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/syseleven/metakube/0.2.1/darwin_amd64/terraform-provider-metakube_v0.2.1 pid=39716 error="exit status 2"
2021/02/02 09:35:47 [TRACE] EvalReadDiff: Read Create change from plan for local_file.kubeconfig
2021/02/02 09:35:47 [TRACE] EvalReadState: reading state for local_file.kubeconfig
2021/02/02 09:35:47 [TRACE] EvalReadState: no state present for local_file.kubeconfig
2021/02/02 09:35:47 [TRACE] EvalReadDiff: Read Create change from plan for local_file.kubeconfig
2021/02/02 09:35:47 [TRACE] EvalReadDiff: Read Create change from plan for metakube_node_deployment.default
2021/02/02 09:35:47 [TRACE] EvalReadState: reading state for metakube_node_deployment.default
2021/02/02 09:35:47 [TRACE] EvalReadState: no state present for metakube_node_deployment.default
2021/02/02 09:35:47 [TRACE] EvalReadDiff: Read Create change from plan for metakube_node_deployment.default
2021/02/02 09:35:47 [ERROR] unknown instance "metakube_cluster.default" referenced during plan
2021/02/02 09:35:47 [TRACE] Re-validating config for "local_file.kubeconfig"
2021/02/02 09:35:47 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/02/02 09:35:47 [ERROR] unknown instance "metakube_cluster.default" referenced during plan
2021/02/02 09:35:47 [WARN] Early exit triggered by hook: *terraform.stopHook
2021/02/02 09:35:47 [TRACE] vertex "local_file.kubeconfig": visit complete
2021/02/02 09:35:47 [TRACE] dag/walk: visiting "provider[\"registry.terraform.io/hashicorp/local\"] (close)"
2021/02/02 09:35:47 [TRACE] Re-validating config for "metakube_node_deployment.default"
2021/02/02 09:35:47 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/02/02 09:35:47 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/local\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2021/02/02 09:35:47 [TRACE] GRPCProvider: Close
2021/02/02 09:35:47 [TRACE] vertex "metakube_node_deployment.default": visit complete
2021/02/02 09:35:47 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/02 09:35:47 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/syseleven/metakube\"] (close)" errored, so skipping
2021-02-02T09:35:47.656+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-02T09:35:47.657+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/local/2.0.0/darwin_amd64/terraform-provider-local_v2.0.0_x5 pid=39715
2021-02-02T09:35:47.657+0100 [DEBUG] plugin: plugin exited
2021/02/02 09:35:47 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/local\"] (close)": visit complete
2021/02/02 09:35:47 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/02/02 09:35:47 [WARN] terraform: stop complete
2021/02/02 09:35:47 [TRACE] backend/local: graceful stop has completed
2021/02/02 09:35:47 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2021/02/02 09:35:47 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 132
2021/02/02 09:35:47 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/02/02 09:35:47 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/02/02 09:35:47 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-02-02T09:35:47.688+0100 [DEBUG] plugin: plugin exited
2021-02-02T09:35:47.689+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-02T09:35:47.692+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/terraform-provider-openstack/openstack/1.35.0/darwin_amd64/terraform-provider-openstack_v1.35.0 pid=39717
2021-02-02T09:35:47.692+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by furkhat** [comment]
Is it consistent? I tried creating a cluster with empty services CIDR and hit Ctrl-C and didn's crash. Can you provide steps to reproduce?

**Comment by furkhat** [comment]
I stumbled upon similar stack trace and in my case it was related to unsafe type conversions. I've fixed them in 0.2.2 release please take a look.

**Comment by uhinze** [comment]
@furkhat looks better in 0.2.2, thanks!

Now I get a similar error when aborting a cluster deletion:
```
metakube_cluster.default: Destroying... [id=trx6pqnrvg:bki1:4b8ttlz8bg]
metakube_cluster.default: Still destroying... [id=trx6pqnrvg:bki1:4b8ttlz8bg, 10s elapsed]
metakube_cluster.default: Still destroying... [id=trx6pqnrvg:bki1:4b8ttlz8bg, 20s elapsed]
metakube_cluster.default: Still destroying... [id=trx6pqnrvg:bki1:4b8ttlz8bg, 30s elapsed]
metakube_cluster.default: Still destroying... [id=trx6pqnrvg:bki1:4b8ttlz8bg, 40s elapsed]
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...

Error: rpc error: code = Canceled desc = context canceled


panic: close of nil channel
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: goroutine 76 [running]:
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).stop(0xc00062f140)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:201 +0x71
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).Stop(0xc00062f140, 0x22eab40, 0xc00068f860, 0xc00068f890, 0xc00062f140, 0xc00068f860, 0xc0008b5ba0)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:215 +0xa5
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_Stop_Handler(0x208c340, 0xc00062f140, 0x22eab40, 0xc00068f860, 0xc0005e4300, 0x0, 0x22eab40, 0xc00068f860, 0x0, 0x0)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:434 +0x214
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000244e00, 0x22f8780, 0xc000603e00, 0xc000383300, 0xc000334510, 0x2b425a8, 0x0, 0x0, 0x0)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).handleStream(0xc000244e00, 0x22f8780, 0xc000603e00, 0xc000383300, 0x0)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008102d0, 0xc000244e00, 0x22f8780, 0xc000603e00, 0xc000383300)
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-22T09:36:55.976+0100 [DEBUG] plugin.terraform-provider-metakube_v0.2.2:         google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021-02-22T09:36:55.979+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/02/22 09:36:55 [DEBUG] metakube_cluster.default: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/02/22 09:36:55 [TRACE] EvalWriteState: writing current state object for metakube_cluster.default
2021-02-22T09:36:55.979+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/syseleven/metakube/0.2.2/darwin_amd64/terraform-provider-metakube_v0.2.2 pid=24013 error="exit status 2"
2021/02/22 09:36:55 [WARN] Early exit triggered by hook: *terraform.stopHook
2021/02/22 09:36:55 [TRACE] vertex "metakube_cluster.default (destroy)": visit complete
2021/02/22 09:36:55 [TRACE] dag/walk: visiting "metakube_cluster.default"
2021/02/22 09:36:55 [TRACE] vertex "metakube_cluster.default": starting visit (*terraform.NodeApplyableResourceInstance)
2021/02/22 09:36:55 [TRACE] EvalReadDiff: Read DeleteThenCreate change from plan for metakube_cluster.default
2021/02/22 09:36:55 [TRACE] EvalReadState: reading state for metakube_cluster.default
2021/02/22 09:36:55 [TRACE] UpgradeResourceState: schema version of metakube_cluster.default is still 0; calling provider "metakube" for any other minor fixups
2021/02/22 09:36:55 [TRACE] GRPCProvider: UpgradeResourceState
2021/02/22 09:36:55 [TRACE] vertex "metakube_cluster.default": visit complete
2021/02/22 09:36:55 [TRACE] dag/walk: upstream of "metakube_node_deployment.default" errored, so skipping
2021/02/22 09:36:55 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/syseleven/metakube\"] (close)" errored, so skipping
2021/02/22 09:36:55 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/22 09:36:55 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/02/22 09:36:55 [TRACE] backend/local: graceful stop has completed
2021/02/22 09:36:55 [WARN] terraform: stop complete
2021/02/22 09:36:55 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/02/22 09:36:55 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 153
2021/02/22 09:36:55 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/02/22 09:36:55 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/02/22 09:36:55 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-02-22T09:36:55.992+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by pierrelex** [comment]
Crash during cluster import hier as well with 0.2.2.

```
terraform --version                                                       1 err | 4s | 14:26:29 
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/syseleven/metakube v0.2.2
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.37.0
```

```
terraform import -var-file "var.tfvars" metakube_cluster.wordpresscluster dpm6sqtwlf:bki1:vp764kwsmw
metakube_cluster.wordpresscluster: Importing from ID "dpm6sqtwlf:bki1:vp764kwsmw"...
metakube_cluster.wordpresscluster: Import prepared!
  Prepared metakube_cluster for import
metakube_cluster.wordpresscluster: Refreshing state... [id=dpm6sqtwlf:bki1:vp764kwsmw]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x118148e]
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: goroutine 16 [running]:
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/syseleven/terraform-provider-metakube/metakube.flattenOpenstackSpec(0x0, 0xc0006e1180, 0x6060572cb3bc0d50, 0x10, 0x126b280)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/syseleven/terraform-provider-metakube/metakube/structure_cluster.go:172 +0xae
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/syseleven/terraform-provider-metakube/metakube.flattenClusterCloudSpec(0x0, 0x0, 0x0, 0xc0000b8080, 0xc000435528, 0x0, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/syseleven/terraform-provider-metakube/metakube/structure_cluster.go:97 +0x191
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/syseleven/terraform-provider-metakube/metakube.flattenClusterSpec(0x0, 0x0, 0x0, 0xc0002118c0, 0xc0005b1bd0, 0x0, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/syseleven/terraform-provider-metakube/metakube/structure_cluster.go:46 +0x2b7
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/syseleven/terraform-provider-metakube/metakube.resourceClusterRead(0x16ec1e0, 0xc00052e5a0, 0xc000212400, 0x12290a0, 0xc000539de0, 0xc00043a980, 0xc00024f8f0, 0x40e0f8)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/syseleven/terraform-provider-metakube/metakube/resource_cluster.go:341 +0xbd6
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001c2630, 0x16ec160, 0xc00011fa00, 0xc000212400, 0x12290a0, 0xc000539de0, 0x0, 0x0, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:287 +0x1ea
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001c2630, 0x16ec160, 0xc00011fa00, 0xc00022a2a0, 0x12290a0, 0xc000539de0, 0xc0000ae1e0, 0x0, 0x0, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:554 +0x1cb
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000635c20, 0x16ec160, 0xc00011fa00, 0xc00011fa40, 0xc00011fa00, 0x1422ac0, 0x148e240)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/grpc_provider.go:571 +0x43b
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0004edde0, 0x16ec160, 0xc00011fa00, 0xc00052e0c0, 0xc0004edde0, 0xc0002d41e0, 0xc0009e8ba0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:297 +0x105
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x148e240, 0xc0004edde0, 0x16ec220, 0xc0002d41e0, 0xc00052e060, 0x0, 0x16ec220, 0xc0002d41e0, 0xc0002021a0, 0xc1)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032a1c0, 0x16f9c60, 0xc000946300, 0xc00077c000, 0xc00047b4d0, 0x1f40310, 0x0, 0x0, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).handleStream(0xc00032a1c0, 0x16f9c60, 0xc000946300, 0xc00077c000, 0x0)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004b6230, 0xc00032a1c0, 0x16f9c60, 0xc000946300, 0xc00077c000)
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-28T14:26:29.814+0200 [DEBUG] plugin.terraform-provider-metakube_v0.2.2: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021-03-28T14:26:29.822+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/syseleven/metakube/0.2.2/linux_amd64/terraform-provider-metakube_v0.2.2 pid=11530 error="exit status 2"
2021-03-28T14:26:29.823+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/03/28 14:26:29 [TRACE] vertex "import metakube_cluster.wordpresscluster result": visit complete
2021/03/28 14:26:29 [TRACE] vertex "metakube_cluster.wordpresscluster (import id \"dpm6sqtwlf:bki1:vp764kwsmw\")": dynamic subgraph encountered errors
2021/03/28 14:26:29 [TRACE] vertex "metakube_cluster.wordpresscluster (import id \"dpm6sqtwlf:bki1:vp764kwsmw\")": visit complete
2021/03/28 14:26:29 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/syseleven/metakube\"] (close)" errored, so skipping
2021/03/28 14:26:29 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/28 14:26:29 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/03/28 14:26:29 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-03-28T14:26:29.830+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by furkhat** [comment]
@pierrelex imports should be fixed in `0.2.3`. I would appreciate if you try it out!

**Comment by furkhat** [comment]
@uhinze could you share your terraform configuration? I can't seem to reproduce the crash when aborting cluster deletion

**Comment by pierrelex** [comment]
Hello @furkhat, I just tested with 0.2.5 and it is working now, thanks!
```
terraform --version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/syseleven/metakube v0.2.5
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.41.0
```
```
terraform import -var-file "var.tfvars" metakube_cluster.wordpresscluster vp764kwsmw 
metakube_cluster.wordpresscluster: Importing from ID "vp764kwsmw"...
metakube_cluster.wordpresscluster: Import prepared!
  Prepared metakube_cluster for import
metakube_cluster.wordpresscluster: Refreshing state... [id=vp764kwsmw]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform
```
